### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2217' in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by JinguangHe** [VikParuchuri/tabled#11]
When I tried to run the entire pdf(https://arxiv.org/pdf/1706.03762) through the default command "tabled DATA_PATH DATA_PATH", I then got the following error: 
`UnicodeEncodeError: 'ascii' codec can't encode character '\u2217' in position 16: ordinal not in range(128)`
But when I processed other pdfs, there's no fault.

**Comment by VikParuchuri** [comment]
Your system encoding is not set to utf-8.  I will force the files to be saved as utf-8 in the next release, which will fix this
