### ISSUE TITLE
How to assign TORCH_DEVICE?

### ISSUE THREAD

**Issue by JinguangHe** [VikParuchuri/tabled#12]
Is there no parameter to assign TORCH_DEVICE 0 or 1 ?

**Comment by JinguangHe** [comment]
> You mean set your cuda device? You can set that with CUDA_VISIBLE_DEVICES . For torch device, like "cuda", "mps", "cpu", you can set via `TORCH_DEVICE`

I have tried to modify settings.py
`settings = Settings(CUDA_VISIBLE_DEVICES=1)`
and created local.env to set "CUDA_VISIBLE_DEVICES=1"
But it didn't work, it always used gpu 0, not 1

**Comment by VikParuchuri** [comment]
You just export CUDA_VISIBLE_DEVICES=1 on the command line - this is an nvidia env variable, has nothing to do with this repo
