### ISSUE TITLE
Chinese may appear garbled.

### ISSUE THREAD

**Issue by dolphinsboy** [VikParuchuri/tabled#14]
[Uploading page0_table0.csv…]()

**Comment by dolphinsboy** [comment]
![Uploading WX20241022-115018.png…]()

**Comment by dolphinsboy** [comment]
![WX20241022-115018](https://github.com/user-attachments/assets/86fed9f4-3970-4005-bcad-c847b3f3f2d1)

**Comment by VikParuchuri** [comment]
You may need to force ocr (detect the cell bboxes).  Sometimes Chinese is not stored properly in PDFs.
