### ISSUE TITLE
Occasionally, letters within a cell are reversed?

### ISSUE THREAD

**Issue by conjuncts** [VikParuchuri/tabled#5]
Please see the example, the paper being https://arxiv.org/pdf/1706.03762

Seems to be pretty rare.

![image](https://github.com/user-attachments/assets/0f98f6e6-c425-4bc0-bf10-aa84e731aa08)

**Comment by VikParuchuri** [comment]
Thanks for reporting!  Oddly, the text seems reversed in the source PDF (we're just extracting chars in PDF order).  Maybe there is a way to fix this, let me see what I can do.

**Comment by VikParuchuri** [comment]
Thanks for the report and the source pdf!  This will be fixed shortly.
