### ISSUE TITLE
Improve OCR Accuracy for Complex Scientific Tables

### ISSUE THREAD

**Issue by taiwanhuachenyu** [VikParuchuri/tabled#6]
![image](https://github.com/user-attachments/assets/988f7640-9b0f-4b60-9723-f5b01602d073)
![image](https://github.com/user-attachments/assets/9ba782bc-cb3b-47a7-832c-b2d16f9961b6)
When recognizing complex tables containing scientific data, the current OCR system exhibits several accuracy issues. The main problems identified are:

Inaccurate table structure recognition: The system fails to correctly identify and preserve the original table's column and row structure and their relationships.
Column header recognition failure: Important column headers such as "Antibody", "VH Chain", "VL Chain" are not correctly recognized, resulting in loss of data context.
Data association errors: Values are not correctly associated with their corresponding column headers, leading to confusion between data from different columns.
Compromised data integrity: Some values (such as binding affinity KD values) are incorrectly split or combined, affecting data accuracy.
Special character and abbreviation recognition issues: Scientific notations like "SEQ ID NO:" and units such as "nM" are not correctly recognized or preserved.

Suggested improvements:

Enhance recognition capabilities for structured scientific data.
Improve algorithms for column header and table header recognition.
Increase accuracy in matching values to their corresponding columns.
Optimize recognition of scientific notations and units.

**Comment by VikParuchuri** [comment]
I am unable to reproduce this using the image you provided:
<img width="796" alt="image" src="https://github.com/user-attachments/assets/359d35ca-309a-4fec-b81d-3035160af573">

Sometimes PDFs have bad text in them.  In this case, use the "detect cell bboxes" option to re-detect the cells and re-OCR the text.  By default, the table text will be extracted from the PDF.
